name: Deploy to Server

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          # Private SSH key stored in GitHub Secrets
          # Required: Generate an SSH key pair and add the private key to GitHub secrets
          # and the public key to the authorized_keys file on your server
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          
      - name: Deploy via SSH
        env:
          # Required: Set the following secrets in your GitHub repository:
          # - SSH_HOST: The hostname or IP address of your server
          # - SSH_USERNAME: The username to connect with
          # - SSH_PORT: The SSH port (usually 22)
          # - REMOTE_PATH: The path on the server where files should be deployed
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
          ENVIRONMENT: ${{ github.event.inputs.environment || 'production' }}
        run: |
          echo "Deploying YAAG Calendar to $ENVIRONMENT environment on $SSH_HOST..."
          
          # Create a directory without node_modules and .git
          mkdir -p deploy
          cp -r css js index.html README.md deploy/
          
          # Deploy files using rsync over SSH
          rsync -avz --delete -e "ssh -p $SSH_PORT" \
            deploy/ \
            $SSH_USERNAME@$SSH_HOST:$REMOTE_PATH
          
          echo "Deployment completed successfully!"